In [3]:
import calendar
print(calendar.month(2022,1))


    January 2022
Mo Tu We Th Fr Sa Su
                1  2
 3  4  5  6  7  8  9
10 11 12 13 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30
31



In [4]:
#two dimensional array
import numpy as np


In [5]:
my_array=np.array([[1,2,3,4,3],[2,4,6,8,5],[1,3,6,8,4]])
print((my_array))

[[1 2 3 4 3]
 [2 4 6 8 5]
 [1 3 6 8 4]]


In [6]:
my_array1=np.insert(my_array,3,[[2,4,6,8,7]],axis=0)
print(my_array1)

[[1 2 3 4 3]
 [2 4 6 8 5]
 [1 3 6 8 4]
 [2 4 6 8 7]]


In [7]:
my_array2=np.insert(my_array,3,[[2,4,6]],axis=1)
print(my_array2)

[[1 2 3 2 4 3]
 [2 4 6 4 8 5]
 [1 3 6 6 8 4]]


In [8]:
len(my_array2[1])


6

In [12]:
def traver(array):
    for i in range(len(array)):
        for j in range(len(array[0])):
            print(array[i][j])
traver(my_array)
                       

1
2
3
4
3
2
4
6
8
5
1
3
6
8
4
